-- 코드를 입력하세요
SELECT
    A.AUTHOR_ID,
    AUTHOR_NAME,
    CATEGORY,
    SUM(PRICE * SALES) AS TOTAL_SALES
FROM 
    AUTHOR A
    JOIN (BOOK B
          JOIN BOOK_SALES BS
          ON B.BOOK_ID = BS.BOOK_ID)
    ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE 
    YEAR(SALES_DATE) = "2022"
    AND
    MONTH(SALES_DATE) = "01"
GROUP BY 
    AUTHOR_NAME,
    CATEGORY
ORDER BY
    AUTHOR_ID,
    CATEGORY DESC