-- 코드를 입력하세요
SELECT PRODUCT_CODE, sum(price * sales_amount) as SALES
# SELECT *
FROM PRODUCT p JOIN OFFLINE_SALE os ON p.PRODUCT_ID = os.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY sum(price * sales_amount) DESC, PRODUCT_CODE
# ORDER BY PRODUCT_CODE