-- 코드를 작성해주세요
SELECT ID, CASE
            WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY) = 1 THEN "LOW"
            WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY) = 2 THEN "MEDIUM"
            WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY) = 3 THEN "HIGH"
            WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY) = 4 THEN "CRITICAL"
         END COLONY_NAME
FROM ECOLI_DATA
ORDER BY ID