-- 코드를 입력하세요
SELECT H.FLAVOR
FROM FIRST_HALF H JOIN JULY J ON H.FLAVOR = J.FLAVOR
GROUP BY H.FLAVOR
ORDER BY SUM(H.TOTAL_ORDER + J.TOTAL_ORDER) DESC
LIMIT 3

# SELECT
#     f.FLAVOR
# FROM
#     FIRST_HALF f INNER JOIN JULY j
#     ON f.FLAVOR = j.FLAVOR
# GROUP BY
#     f.FLAVOR
# ORDER BY
#     SUM(f.TOTAL_ORDER + j.TOTAL_ORDER) DESC
# LIMIT 3;
