-- 코드를 입력하세요
WITH RECURSIVE TIME AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM TIME WHERE HOUR < 23
)

SELECT T.HOUR as HOUR, COUNT(O.DATETIME)
FROM ANIMAL_OUTS O RIGHT JOIN TIME T ON HOUR(O.DATETIME) = T.HOUR
GROUP BY T.HOUR
ORDER BY T.HOUR