-- 코드를 입력하세요
SELECT ugb.TITLE, ugb.BOARD_ID, REPLY_ID, ugr.WRITER_ID, ugr.CONTENTS, DATE_FORMAT(ugr.CREATED_DATE, "%Y-%m-%d") as CREATED_DATE
FROM USED_GOODS_BOARD ugb JOIN USED_GOODS_REPLY ugr ON ugb.BOARD_ID = ugr.BOARD_ID
# WHERE DATE_FORMAT(ugb.CREATED_DATE, "%Y-%m") = "2022-10"
WHERE ugb.CREATED_DATE BETWEEN "2022-10-01" AND "2022-10-30"
ORDER BY ugr.CREATED_DATE ASC, ugb.TITLE ASC