# -- 코드를 작성해주세요
WITH TLB AS (
    SELECT *, CASE
                WHEN LENGTH <= 10 or LENGTH IS NULL THEN 10
                ELSE LENGTH
              END AS FINALLY_LENGTH
    FROM FISH_INFO
)

SELECT
    COUNT(*) as FISH_COUNT,
    MAX(FINALLY_LENGTH) as MAX_LENGTH,
    FISH_TYPE
FROM
    TLB
GROUP BY
    FISH_TYPE
HAVING
    AVG(FINALLY_LENGTH) >= 33
ORDER BY 
    FISH_TYPE